FROM node:16-alpine

COPY ./ /home/node/app

WORKDIR /home/node/app

RUN npm install bcrypt jsonwebtoken atob cookie-parser dotenv ejs express mongoose http-errors morgan

RUN npm install --global nodemon
